### ISSUE TITLE
Requests are sometimes routed to root page when requesting childpage

### ISSUE THREAD

**Issue by hkurhinen** [Metatavu/kunta-api-www#49]

**Comment by anttileppa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [URL on oikea, mutta jostain syystä sivu reitittyy väärin? (Tämä on hieman erikoinen bugi)](https://trello.com/c/L4Ehtl5f/129-url-on-oikea-mutta-jostain-syysta-sivu-reitittyy-vaarin-tama-on-hieman-erikoinen-bugi)
