### ISSUE TITLE
Fragment module

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/kunta-api-www#9]
As a develoeper i would like to have a fragment module

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [footer](https://trello.com/c/UzpNTHyT/10-footer)

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Osallistu ja vaikuta -osion toteutus](https://trello.com/c/SowSmqmL/54-osallistu-ja-vaikuta-osion-toteutus)
